### ISSUE TITLE
VS 2015 support

### ISSUE THREAD

**Issue by mathiasdue** [natevoci/KeyboardRedirector#1]
Hi Nate,

Do you have this in a VS2015 version? :-) 
When i try to convert it to VS2015 .Net 4.5, the hook doesn't send any messages.
Is it because the hook is compiled for .Net 4.0? 

Sorry for posting this as an issue, but i could not find another way of contacting you - tried to sign up at the forum, but I'm not allowed to post.. :-)

**Comment by natevoci** [comment]
No, sorry. I haven't upgraded to VS2015. I'm still on VS2012 for work so I haven't bothered.

The hook is either a 32bit or 64bit native dll. It doesn't have any .NET in it, so it shouldn't matter if the main app is compiled with 4.0 or 4.5. It just has to use the correct bitness dll for the system it is running on.

No worries about posting here. The forum has been pretty much shut down from new users since it was getting bombarded with spam.

**Comment by natevoci** [comment]
I've just updated the project to build with VS 2015 Community
